### ISSUE TITLE
where did transformer come from ?

### ISSUE THREAD

**Issue by weiyinfu** [ericeslinger/delta-transform-html#2]
I cannot understand the demo: where did transformer come from ?
```js
const htmlString = transformer.transform(testVal);
```

**Comment by ericeslinger** [comment]
Ah, sorry - that's a typo in the example code. There should be a `const
transformer = new Formatter();` in there. The Formatter class can be
extended to override how formats are output (e.g., how italic is created,
using <em> fields or span class="italic-display" or something else), but
the base Formatter class should work pretty well well. The code in the test
directory might be a better example.
